# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Rockhead.sln
    - name: Build
      run: dotnet build --no-restore src/Rockhead.sln
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::204847680503:role/github-actions-role
        aws-region: us-east-1
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" src/Rockhead.sln || true
    - name: Test Report
      uses: dorny/test-reporter@v1.8.0
      if: always()
      with:
        name: Test Report
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
